apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jcode-vol-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 900Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jcode-starter-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-worker1-r1
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jcode-archive-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-worker1-r1
  resources:
    requests:
      storage: 100Gi
