apiVersion: v1
kind: ConfigMap
metadata:
  name: jcode-generator-configmap
  namespace: watcher
data:
  ALGORITHM: "HS256"
  NFS_SERVER: "your.nfs.server.address"
  NFS_PATH: "/yourPath"
  SNAPSHOT_NFS_SERVER: "your.nfs.snapshot.server.address"
  SNAPSHOT_NFS_PATH: "/yourSnapshotPath"
  SERVICE_ACCOUNT: "deployment-controller"
  CODE_SERVER_IMAGE: "code-server:test"
  CODE_SERVER_VNC_IMAGE: "code-server-vnc:test"
  IMAGE_PULL_POLICY: "IfNotPresent"
  STARTER_ZIP_MAX_BYTES: "52428800"
  STARTER_ZIP_MAX_UNCOMPRESSED_BYTES: "209715200"
  STARTER_ZIP_MAX_FILES: "1000"
---
apiVersion: v1
kind: Secret
metadata:
  name: jcode-generator-secret
  namespace: watcher
type: Opaque
data:
  SECRET_KEY: "WU9VUl9TRUNSRVRfS0VZX0JBU0U2NA==" # ("YOUR_SECRET_KEY_BASE64")
