apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap-controller.yaml
  - workspace-controller.yaml
  - router.yaml
  - squid-exporter.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: jcode
    includeSelectors: false
